### ISSUE TITLE
Poor Performance with Movidius VPU

### ISSUE THREAD

**Issue by TheRedCross** [incluit/OpenVino-For-SmartCity#10]
Hi,
When I was running the program using CPU, the performance was outstanding, but when I attempted the run the script

./intel64/Release/smart_city_tutorial -m_vp $vehicle232 -d_vp HDDL -i ../data/NewVideo2.mp4

The performance was poor, with barely 5 frames per second. The device I am currently using for VPU is IEI Mustang-V100-MX8. The device was set up correctly, and it could run the Openvino demos just fine. 

Is the program compatible with HDDLs, and has it been tested before? Or is there a problem on my end that I might have overlooked?

**Comment by HernanG234** [comment]
Hi @TheRedCross,

We don't count on that hardware and at the moment we started developing this, it didn't practically exist I believe. That's why we don't support it right now.

Anyway, here's a working example on how to load the plugins accordingly for the device:
https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo

If you can make it work and submit a pull-request with the changes, we'll accept it undoubtedly.

Hope you can do it! Let us know how it goes

Cheers

**Comment by TheRedCross** [comment]
Thanks for the reply!

When the proper drivers are installed, HDDL could work just fine. However, the performance would be much, much better if it is used in asynchronous mode. My mistake for not experimenting more before asking. Thanks again!

**Comment by HernanG234** [comment]
We'll be waiting that PR!
Cheers!
